# docker-compose.yml
version: '3.8'

services:
  db:
    # We use Alpine Linux because it is incredibly lightweight and secure
    image: postgres:15-alpine
    container_name: aero_rag_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234  # This must match your backend/.env file
      POSTGRES_DB: aero_rag_db         # This must match your backend/.env file
    ports:
      - "5432:5432"
    volumes:
      # This ensures your database data survives even if the container is destroyed
      - postgres_data:/var/lib/postgresql/data

# --- Your Vector Database ---
  qdrant:
    image: qdrant/qdrant:latest
    container_name: aero_vector_db
    restart: always
    ports:
      - "6333:6333" # REST API (for checking status)
      - "6334:6334" # gRPC (for high-speed Python communication)
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data: